# Generated by Django 5.0.6 on 2024-06-04 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajador',
            name='tiempo_trabajado',
        ),
    ]
