# Generated by Django 5.0.4 on 2024-06-05 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0002_remove_trabajador_tiempo_trabajado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajador',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='tiempo_entrada',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='tiempo_salida',
        ),
        migrations.CreateModel(
            name='RegistroTiempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tiempo_entrada', models.TimeField()),
                ('tiempo_salida', models.TimeField()),
                ('tiempo_trabajado', models.TimeField(blank=True, null=True)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajadores.trabajador')),
            ],
        ),
    ]
