// <auto-generated />
using System;
using BackEndNETLINUX.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackEndNETLINUX.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240625210541_InitialCreatee")]
    partial class InitialCreatee
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackEndNETLINUX.Models.RegistroTiempo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("TiempoEntrada")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("TiempoSalida")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("TiempoTrabajado")
                        .HasColumnType("time");

                    b.Property<int>("TrabajadorID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("TrabajadorID");

                    b.ToTable("RegistrosTiempo");
                });

            modelBuilder.Entity("BackEndNETLINUX.Models.Trabajador", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.HasKey("ID");

                    b.ToTable("Trabajadores");
                });

            modelBuilder.Entity("BackEndNETLINUX.Models.RegistroTiempo", b =>
                {
                    b.HasOne("BackEndNETLINUX.Models.Trabajador", "Trabajador")
                        .WithMany()
                        .HasForeignKey("TrabajadorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trabajador");
                });
#pragma warning restore 612, 618
        }
    }
}
